"""
Type aliases for SpritePal to improve type safety and readability.

DEPRECATED: This module re-exports from core.types for backward compatibility.
New code should import directly from core.types.
"""
from __future__ import annotations

# Re-export all from the canonical location
from core.types import (
    BoolSignal,
    CacheData,
    CacheKey,
    CachePath,
    CacheStats,
    ConfigDict,
    DialogResult,
    DictSignal,
    ErrorCallback,
    FilePath,
    ImageMode,
    ImageSize,
    IntSignal,
    ListSignal,
    NavigationHint,
    OperationName,
    OperationProgress,
    OperationResult,
    OutputPath,
    PaletteData,
    PILImage,
    PreviewPixmap,
    PreviewSize,
    ProgressCallback,
    RegionMap,
    RGBColor,
    ROMData,
    SearchResults,
    SettingsValue,
    SimilarityResult,
    SimilarityScore,
    SpriteData,
    SpriteLocation,
    SpriteOffset,
    StringSignal,
    TileCount,
    TileData,
    TileMatrix,
    ValidationResult,
    WidgetParent,
    WorkerCallback,
)

__all__ = [
    "PILImage",
    "ImageMode",
    "ImageSize",
    "TileMatrix",
    "SpriteData",
    "SimilarityScore",
    "SpriteOffset",
    "SimilarityResult",
    "SearchResults",
    "PaletteData",
    "RGBColor",
    "ROMData",
    "TileData",
    "PreviewPixmap",
    "PreviewSize",
    "TileCount",
    "WorkerCallback",
    "ProgressCallback",
    "ErrorCallback",
    "WidgetParent",
    "DialogResult",
    "FilePath",
    "OutputPath",
    "CachePath",
    "ConfigDict",
    "SettingsValue",
    "ValidationResult",
    "StringSignal",
    "IntSignal",
    "BoolSignal",
    "ListSignal",
    "DictSignal",
    "OperationName",
    "OperationResult",
    "OperationProgress",
    "CacheKey",
    "CacheData",
    "CacheStats",
    "NavigationHint",
    "SpriteLocation",
    "RegionMap",
]
